### ISSUE TITLE
Installation issue  [NixOS]

### ISSUE THREAD

**Issue by Creator54** [metacall/install#3]
![share](https://user-images.githubusercontent.com/34543609/114843868-e33f6e00-9df7-11eb-867e-c03eca186ef2.png)

**Comment by giarve** [comment]
Instead of modifying `/etc/profile` (which is global and readonly in the case of NixOS, as expected) we should add a new file under `/etc/profile.d` because the line added is application specific and check if the shell is `fish` because the exporting of the variables is different than other shells (bash, zsh..).

**Comment by Creator54** [comment]
As per /etc/profile it doesnt seem to check for the profile.d dir so I appended to profile.local 
seems to works only with bash shell.
![share](https://user-images.githubusercontent.com/34543609/114888478-e69e1e00-9e26-11eb-861b-b2fd8b66cd36.png)

**Comment by viferga** [comment]
@Creator54 Sorry for late reply, I did not notice about this issue.
Here's the patch: https://github.com/metacall/install/commit/e07ae8b27a66916769977c3eb7a50f7d8e1614a4
